version: '3.8'
services:
  db:
    container_name: "weather"
    image: postgres:14.1-alpine
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=weather

    ports:
      - "5432:5432"

    networks:
      - custom

networks:
  custom:
    driver: bridge
